name: Update extension from RSS

on: 
  workflow_dispatch:
  schedule:
  - cron: "24 13,15,17,18,19,21,23,1 * * *"

jobs:
  run_extension_update:
    name: run extension update python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f extension/requirements.txt ]; then pip install -r extension/requirements.txt; fi
    - name: Run the program
      run: |
        python extension/extension.py
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
